const CONTRIBUTORS = [
  {
    "name": "4 Colours",
    "slug": "4-colours",
    "bio": "basement sounds for the more mature listener.pack the essentials for a journey into the deep reaches of house, techno, broken beat, soul, and funk with cambridge's finest audio pilot.4c has been gracing the airwaves for years via future music, mhyh, frission radio, motion fm, and ugs. he currently delivers his one foot in the chill show on d3ep radio. salute sir!",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/v1774810670/4colours_8qnj_ohfxed.jpg",
    "instagram": "",
    "mixcloud": "",
    "soundcloud": "https://soundcloud.com/4colours",
    "schedule": "sun 10pm",
    "active": true
  },
  {
    "name": "Mark Disc Break",
    "slug": "mark-disc-break",
    "bio": "mark disc break curates the station playlists and the evening garage house sessions. expect all genres from the dancefloor to the sofa. heavy underground shufflers, funky bubblers, and soul-tinged jazzy nibblers.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/markdiscbreak2_kpeaps.png",
    "instagram": "",
    "mixcloud": "",
    "soundcloud": "",
    "schedule": "fri 10pm",
    "active": true
  },
  {
    "name": "Look Busy Collective",
    "slug": "look-busy-collective",
    "bio": "look busy is a collective of djs with our roots firmly in collecting and mixing wonky records on belt drive turntables. between us we have over 60 years of experience looking busy behind the decks and counting.you can find us playing across Scotland in various clubs, bars and festivals as well as on podcasts or radio shows such as rhythmcast, berlin boombox, house salad and making waves underground.our club nights and festival appearances have supported and booked djs that include dam swindle, dj sneak, dusky, paul woolford, george fitzgerald, dh haus, brawther, robert owens, mella dee, slam, horse meat disco, mk, booka shade, chaos in the cbd, darius syrossian, green velvet, purple disco machine, basement jaxx, john digweed, james zabeila, palms trax, jamie trench, oli furness and ejeca.this project is our creative platform to celebrate and share our collective love for house music, funk, soul, disco and any oddity or curve ball we come across in-between.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/v1774810669/lookbusycollective_ruqmj1.png",
    "instagram": "https://www.instagram.com/look_busy_collective/",
    "mixcloud": "",
    "soundcloud": "https://soundcloud.com/look_busy_collective",
    "schedule": "sat 10pm",
    "active": true
  },
  {
    "name": "Semi-Detached Disco",
    "slug": "semi-detached-disco",
    "bio": "from amsterdam with love.djs and part-time space cadets, leroy hemp and henry poynor take us on an interplanetary journey to the finest space disco in the solar system.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/semi_detached_2024_gj1ahs.png",
    "instagram": "",
    "mixcloud": "",
    "soundcloud": "https://soundcloud.com/semidetachedcloud/sets",
    "schedule": "sun 6pm",
    "active": true
  },
  {
    "name": "Dust Down Records",
    "slug": "dust-down-records",
    "bio": "\"time to dust ourselves down\"record label & dj collective, south london via the universe, from brothers @duvet-dave & @joeginho",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/v1774810667/Dust_Down_Records_2TJa_m7orsl.jpg",
    "instagram": "",
    "mixcloud": "",
    "soundcloud": "https://soundcloud.com/dustdownrecords",
    "schedule": "fri 6pm",
    "active": true
  },
  {
    "name": "Disco Borisco Soundsystem",
    "slug": "dbs",
    "bio": "disco-borisco soundsystem is a ukrainian project based in france. fueled by the international creative community, oleksiy is focused on building bridges and sharing positive energy via disco, funk, and house music.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/dbs_rkb7jf.png",
    "instagram": "",
    "mixcloud": "",
    "soundcloud": "https://soundcloud.com/dbs011010",
    "schedule": "sat 5pm",
    "active": true
  },
  {
    "name": "Sister Shaft",
    "slug": "sister-shaft",
    "bio": "sister shaft brings together the juiciest bits of jazz, funk, soul and everything in close proximity. a member of the #bamboocrew and recent addition to the #melomaniacs collective, she likes to get you jigging to a good jam.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/sister_shaft_o9dgo8.png",
    "instagram": "https://www.instagram.com/sister_shaft/",
    "mixcloud": "https://www.mixcloud.com/sister_shaft/",
    "soundcloud": "",
    "schedule": "",
    "active": false
  },
  {
    "name": "Adeleamis",
    "slug": "adeleamis",
    "bio": "adele made her djing debut in may 2022 with the melomaniacs collective at run dem radio. bitten by the djing bug, she invested in a set of decks and hasn't looked back. playing a mix of vinyl and digital across the genres of soul, funk, jazz, latin, brazilian, afro beat, disco and house.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/adeleamis_hlgsob.png",
    "instagram": "https://www.instagram.com/adeleamis/",
    "mixcloud": "https://www.mixcloud.com/Adelamis/",
    "soundcloud": "",
    "schedule": "",
    "active": false
  },
  {
    "name": "Francois de Bonsoir",
    "slug": "francois-de-bonsoir",
    "bio": "a keen cyclist, flaneur and oenophile, francois de bonsoir serves up the finest flavours from the broken beat, nu jazz and deep house kitchen.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/francoisdebonsoirNEW_zj9x9c.png",
    "instagram": "https://www.instagram.com/francois_de_bonsoir/",
    "mixcloud": "https://www.mixcloud.com/Francois_de_Bonsoir/",
    "soundcloud": "",
    "schedule": "sat 6pm",
    "active": true
  },
  {
    "name": "Lee Tristram",
    "slug": "lee-tristram",
    "bio": "lee's journey as a dj began in 1989. he has played in some of the capital's main clubs such as ministry, turnmills, and the cross & egg, plus pacha and the '99 wmc in miami.he has since moved onto production, releasing a string of solo and remix projects.we're delighted to welcome Lee's unique, deep and soulful house style to the station!",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/leetristram_ls1o6x.png",
    "instagram": "",
    "mixcloud": "https://www.mixcloud.com/leetristram/",
    "soundcloud": "",
    "schedule": "",
    "active": false
  },
  {
    "name": "Chopped Herring Records",
    "slug": "chopped-herring-records",
    "bio": "\u201cthe biggest thrills still come from the unearthing of barely heard music from artists who might have slipped through history\u2019s cracks. That is what the british label Chopped Herring Records specializes in\u2026. \u201cnew york timesjoin us for a weekly series featuring dj mixes from the chopped herring records 'fly fishing' mixtape series. showcasing the likes of dj woody, ca$h money, p.f. cuttin', chubby grooves & more. this is a real treat.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/v1774810667/CHOPPED_HERRING_RECORDS_fmsaio.jpg",
    "instagram": "",
    "mixcloud": "",
    "soundcloud": "https://soundcloud.com/chopped-herring-records",
    "schedule": "",
    "active": false
  },
  {
    "name": "Mike Edwards",
    "slug": "mike-edwards",
    "bio": "mike has been djing for over two decades and plays a wide range of styles with a focus on the disco/house spectrum.mike has featured at nights including majestik, rhythm, let it bleed, and enjoy music.a founding member of the look busy dj collective we're excited and honoured to have Mike contributing to the station.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/mike_edwards_uf0tkl.png",
    "instagram": "",
    "mixcloud": "",
    "soundcloud": "https://soundcloud.com/look_busy_collective",
    "schedule": "sat 10pm",
    "active": true
  },
  {
    "name": "Kev Reid",
    "slug": "kev-reid",
    "bio": "kev has been djing since 1997 and has been a regular fixture in the popular bars & nightclubs of aberdeen since.he runs nights under the majestik guise which have attracted paul woolford, detroit swindle, brawther, dusky, green velvet & josh butler.kev is part of the look busy collective and we're delighted to have his signature soulful sound on disc break.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/kev_reid_rwdk0y.png",
    "instagram": "",
    "mixcloud": "",
    "soundcloud": "https://soundcloud.com/look_busy_collective",
    "schedule": "sat 10pm",
    "active": true
  },
  {
    "name": "Andy Buchan",
    "slug": "andy-buchan",
    "bio": "aberdeen-based dj / producer andy buchan is a busy man. when he's not in the studio, andy runs club nights and a podcast series 'rhythmcast'.as a member of the look busy collective, andy's emphasis is on \"collecting records that will stand the test of time.\"catch him playing regularly around clubs in scotland, festivals, and warming up for artists such as chaos in the cbd, horse meat disco, mella dee, purple disco machine, brawther, ejeca, sven weisemann, and robert owens.it's a pleasure to welcome andy to the disc break lineup.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/v1774810665/andy_buchan_s3aajm.png",
    "instagram": "",
    "mixcloud": "",
    "soundcloud": "https://soundcloud.com/look_busy_collective",
    "schedule": "sat 10pm",
    "active": true
  },
  {
    "name": "Elijah Tiger",
    "slug": "elijah-tiger",
    "bio": "elijah tiger brings back the soul.a quiet storm which brews into a cross-genre revolution.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/elijah_gchjvu.png",
    "instagram": "",
    "mixcloud": "https://www.mixcloud.com/ElijahTiiger/",
    "soundcloud": "",
    "schedule": "",
    "active": false
  },
  {
    "name": "Jay Blundell",
    "slug": "jay-blundell",
    "bio": "Jay has been in the music industry for nearly 30 years, behind the decks or at a desk! His genre selection is wide (nearly as wide as the shelves holding his 10,000+ records!). For Disc Break, he's treated us to his unique blend of dancefloor-friendly deep disco. Always a pleasure!",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/jayblundell_nlkypk.png",
    "instagram": "",
    "mixcloud": "https://www.mixcloud.com/REDI_Knights/",
    "soundcloud": "",
    "schedule": "",
    "active": false
  },
  {
    "name": "Jake Parker",
    "slug": "jake-parker",
    "bio": "Soaking up the sounds from around the globe. Keen back-packer Jake Parker conjures up a playlist based on the South American countries and cities he regularly frequents.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/jake_akgxc6.png",
    "instagram": "",
    "mixcloud": "",
    "soundcloud": "",
    "schedule": "",
    "active": false
  },
  {
    "name": "Wh0 Plays Sessions",
    "slug": "wh0",
    "bio": "wh0 plays sessions is a worldwide radio show, with a fresh episode each week. hosted by wh0 plays records & presented by six resident djs - wh0, forbid, bad intentions, dial9, jacq (uk) & josh hunter.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/v1774810664/WHO_PLAYS_ewr97j.jpg",
    "instagram": "https://www.instagram.com/thisiswh0/",
    "mixcloud": "",
    "soundcloud": "https://soundcloud.com/thisiswh0",
    "schedule": "",
    "active": false
  },
  {
    "name": "Willy",
    "slug": "willy",
    "bio": "born southerner, bred northerner with a love for an eclectic mix of genres and artists. curating a perfectly imperfect selection of jazz, soul, disco and world records from the collection. all love, all vinyl.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/willy_tduqxh.png",
    "instagram": "",
    "mixcloud": "https://www.mixcloud.com/Willydeamer/",
    "soundcloud": "",
    "schedule": "sun 5pm",
    "active": true
  },
  {
    "name": "Alex Moore",
    "slug": "alex-moore",
    "bio": "manchester born alex specialises in disco & funk but is comfortable across all styles blending in house and techno seamlessly. he's played at yes & wilson\u2019s den in the city centre and has regular weekly residencies at bars in manchester. alex can be seen hosting and playing at his own events in manchester with lots more coming in the future.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/alex_moore_mbyrst.png",
    "instagram": "https://www.instagram.com/alexmooremusic/",
    "mixcloud": "",
    "soundcloud": "https://soundcloud.com/alexmooremcr",
    "schedule": "sun 8pm",
    "active": true
  },
  {
    "name": "Pollen",
    "slug": "pollen",
    "bio": "record collector and vinyl dj oli shenton is a resident at froot radio and former resident of 'love dose' and 'we\u2019re not normal' parties at stealth, nottingham. mainly focussed on classic and contemporary techno and house, but looking forward to also sharing the eclectic side of collection of rarer cuts of italo, new beat, and boogie on the show.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/oli_shenton_vo32da.png",
    "instagram": "https://www.instagram.com/pollensound/",
    "mixcloud": "",
    "soundcloud": "",
    "schedule": "",
    "active": false
  },
  {
    "name": "Martin Depp",
    "slug": "martin-depp",
    "bio": "london based house & garage producer, dj and pogo house records founder. started on rave scene as dj and producer at early '90 were finally around 2010 discovered his love for deep and underground house vibes with early garage house influences. this passion persists to this day where the result of this is plenty of releases and remixes on his pogo house records and also on plastik people, soul revolution, gents & dandy's records, onward recordings, white widow records, xylo, pure beats records or urban impulz records.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/martin_depp_jbkfo9.png",
    "instagram": "http://www.instagram.com/martin_depp",
    "mixcloud": "http://www.mixcloud.com/martindeppmusic",
    "soundcloud": "http://www.soundcloud.com/martindepp",
    "schedule": "sat 8pm",
    "active": true
  },
  {
    "name": "Jostun",
    "slug": "jostun",
    "bio": "A balearic journey from slo-mo chuggers to dreamy italo house via afro-latin grooves, leftfield disco and underground soul.Based in Manchester, Jostun embarked on his DJ journey in the city's underground clubs more than a decade ago. Over the years he has cultivated a versatile style, effortlessly navigating between commanding a bustling dancefloor and crafting laid-back vibes on a sun-kissed afternoon.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/jostun_cropped_xwam9w.png",
    "instagram": "https://www.instagram.com/jostun_music/",
    "mixcloud": "https://www.mixcloud.com/jostun/",
    "soundcloud": "https://soundcloud.com/jostun",
    "schedule": "",
    "active": false
  },
  {
    "name": "Tide and Time (Angus)",
    "slug": "angus",
    "bio": "Angus developed his passion for exhilarating and emotive club cuts during his Midlands based residencies at Shadow City and MoodFix. His recent move to Manchester coincided with a deeper exploration of ambient and leftfield electronica via his Reform Radio and Borderless Grooves features. His selection draws inspiration from club culture and the natural world in equal measure.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/angus_tide_and_time_on0mtp.png",
    "instagram": "https://www.instagram.com/angus_jsp/",
    "mixcloud": "",
    "soundcloud": "https://soundcloud.com/outershellsounds",
    "schedule": "sun 7pm",
    "active": true
  },
  {
    "name": "Mark A (Soul Buggin')",
    "slug": "mark-a",
    "bio": "Mark is one quarter of the Soul Buggin\u2019 crew, one of the most respected DJ ensembles and nights in Nottingham. \u201cRooted in Soul\u201d is how Mark describes his selections; expect deep, bumpy, soulful, garage, classic, basement vibe house along with disco, boogie, jazz funk, broken beat and more!Soul Buggin\u2019 is renowned for throwing atmospheric, unpretentious and downright excellent parties featuring an impressive array of headliners. With over a hundred events under their collective belt, Soul Buggin\u2019 celebrate their 20th birthday during 2024. Check out the Soul Buggin' Facebook & Instagram profiles.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/Mark_A_upweh6.png",
    "instagram": "https://www.instagram.com/markalcock1/",
    "mixcloud": "https://www.mixcloud.com/markalcock/",
    "soundcloud": "",
    "schedule": "sat 9pm",
    "active": true
  },
  {
    "name": "Powdersoul",
    "slug": "powdersoul",
    "bio": "Introduced to 'proper' house music through mid 90\u2019s Kiss FM radio shows from the likes of DJ\u2019s Paul \u2018Trouble\u2019 Anderson, Steve Jackson and Bobbi & Steve providing the perfect education to jump start the thirst for the 1000\u2019s and 1000\u2019s of records in his collection. Music ethic has always been to keep an eye on the new but never forgetting the old and is representative of his DJ sets where you will hear upfront tracks alongside those rare 1993/94 dubs weaved in with house and garage belters. DJ wise, a quarter of the London\u2019s Soulfulbeats DJ collective who has provided the capital with some of the best soulful party moments, playing alongside the talents of Sean McCabe, Groove Assassin, Phil Asher and Craig Smith, but also guesting at many of the UK\u2019s finer house music events alongside the likes of Louie Vega and Paul \u2018Trouble\u2019 Anderson. Young family life has meant repointing energy and easing off the musical gas for a bit, but in the meantime check out his music channel (Melly Mel Records) on the Instagram link below",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/Powdersoul_hdly0o.png",
    "instagram": "https://www.instagram.com/melly_melv_records",
    "mixcloud": "",
    "soundcloud": "",
    "schedule": "fri 9pm",
    "active": true
  },
  {
    "name": "Shi Karim",
    "slug": "shi-karim",
    "bio": "Shi Karim has been collecting vinyl and DJing since the early 90's and over the decades has promoted and DJ'd at many venues around the North West. He continues to buy and collect vinyl and his eclectic style covers anything from Hip Hop and soul, broken beat, rare groove and disco to low tempo house. He co-runs a local monthly night which he started in 2023.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/shikarim_olnhpl.png",
    "instagram": "https://www.instagram.com/shikarim78/",
    "mixcloud": "",
    "soundcloud": "https://soundcloud.com/shikarim",
    "schedule": "fri 8pm",
    "active": true
  },
  {
    "name": "DJ Sol",
    "slug": "dj-sol",
    "bio": "DJ Sol started djing in 2002 as a student in Aberdeen, and after a chance meeting with Craig Smith (6th Borough Project, Soul Renegades, Soul Heaven) while he was dropping a set at Ponana, Aberdeen, Sol developed a deep love for house music. After moving to Edinburgh in 2003, Sol had residences in some of Edinburgh's top clubs and bars before moving back home to London. Sol's main musical influences include Louie Vega, Masters at Work, Craig Smith, Sean McCabe, Incognito, Neil Pierce, Terry Hunter, Black Coffee, Jimpster and Atjazz. Sol's goal is to put together sets that can uplift, shift people's moods and mindsets into positivity, and that create places for rest. Expect journeys into the deep and soulful with Sol!",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/v1774810663/DJSol_iuicts.png",
    "instagram": "",
    "mixcloud": "",
    "soundcloud": "https://soundcloud.com/sol_obi",
    "schedule": "sat 7pm",
    "active": true
  },
  {
    "name": "Juan Groove",
    "slug": "juan-groove",
    "bio": "Juan began spinning vinyl at 16 and has continued to do so for 25 plus years. His journey expanded during residencies in Spain and Andorra in the early 2000\u2019s, deepening his connection to music and people. Since then, he has mastered blending vinyl and digital formats, creating unforgettable sets that take listeners on soul-stirring journeys. His soulful, deep, and sexy disco beats keep dance floors alive all night. But he doesn\u2019t stop there. Juan\u2019s sets span House, Drum and Bass, Disco, UK Garage, French Touche, and beyond. Ensuring every performance is unique. Influenced by his father\u2019s love of jazz and disco, his creativity shines through diverse selections shaped by iconic labels such as Defected, Yellow Productions, Soulfuric, Roul\u00e9 and Blue Note. Juan takes inspiration from his artists including Moodymann, Louie Vega, DJ Gregory and Jimpster. Check out Juan's VinylGateway Instagram account for regular posts from his collection.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/v1774810663/Juan_Groove_Logo_y3ahlh.png",
    "instagram": "https://www.instagram.com/vinylgateway",
    "mixcloud": "",
    "soundcloud": "https://soundcloud.com/juannationunderagroove?fbclid=PAZXh0bgNhZW0CMTEAAaZdDVguS21VslRhC_pJgeMOPRXQRYoszctqU8OzfGn3uEjfQqwHv0EE5M0_aem_vQKuEFODzsdAH6l59YE1Vw",
    "schedule": "Rhythm Rotation fri 7pm",
    "active": true
  },
  {
    "name": "DJ GoodVibes",
    "slug": "dj-goodvibes",
    "bio": "Vinyl DJ since 1993 and collector at heart, influenced by the house styles of Chicago, New York and England.Co-founder of the Minimal Records store in Nancy from 1996 to 2001. Resident DJ at GotMilk parties in Strasbourg from 1993 to 1997 and member of the B-product team.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/DJ_Good_Vibes_qcmpu4.png",
    "instagram": "https://www.instagram.com/djgoodvibes/?hl=en",
    "mixcloud": "",
    "soundcloud": "https://soundcloud.com/djgoodvibes67",
    "schedule": "sun 9pm",
    "active": true
  },
  {
    "name": "Fuse",
    "slug": "fuse",
    "bio": "Hailing from the Bay Area and heavily influenced by the 90\u2019s boom bap hip hop sound, Fuse started spinning in 2000. Initially playing Drum & Bass, he founded Deadline Sound System, an all D&B crew responsible for bringing a slew of talent from across the US and UK.Throughout the years, inspired by his older brother, an already-established house DJ, Fuse began exploring Downtempo and House music, gradually carving out his own distinct sound. As a passionate digger, he strives to play tracks that aren\u2019t currently sitting in everybody\u2019s playlists, covering a variety of genres and taking the audience on a journey through tunes they forgot they loved or never knew existed.Artists he draws inspiration from include DJ Steef, Aroop Roy, Dam Swindle, Tuccillo, and Jkriv.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/fuse_xt1svg.png",
    "instagram": "https://www.instagram.com/fuse.music.ca/",
    "mixcloud": "",
    "soundcloud": "",
    "schedule": "Rhythm Rotation fri 7pm",
    "active": true
  },
  {
    "name": "Sounds of Harris",
    "slug": "sounds-of-harris",
    "bio": "Sounds of Harris is the pseudonym of Marley Harris, a young DJ who grew out of Southampton\u2019s thriving vinyl scene and is now residing in Brighton.You can catch him playing bars and clubs across the South coast playing an uplifting mix of disco, soul, house and garage guaranteed to bring good times and stir the soul.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/marleyharris_asnxw0.png",
    "instagram": "https://www.instagram.com/soundsofharris/",
    "mixcloud": "",
    "soundcloud": "https://soundcloud.com/marley-harris-128069212",
    "schedule": "Rhythm Rotation fri 7pm",
    "active": true
  },
  {
    "name": "Flavio",
    "slug": "flavio",
    "bio": "Fl\u00e1vio is a Manchester based, multi genre dj, coming with an hour of groovy old school disco, boogie and deep house to get you in the right mood for new years. His usual sets can include everything from disco & boogie, through to hip-hop, electro, techno, tech house, deep house and uk garage (to name a few).You can find him on Instagram or TikTok @flavio90z",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/flavio_mgwdjt.png",
    "instagram": "https://www.instagram.com/flavio90z/",
    "mixcloud": "",
    "soundcloud": "",
    "schedule": "Rhythm Rotation fri 7pm",
    "active": true
  },
  {
    "name": "Alan Tonkinson",
    "slug": "alan-tonkinson",
    "bio": "Alan's signature sound is anchored by a wonky deviant disco bassline, then seamlessly segues through Balearic rhythms, late night NYC boogie and classic Detroit house music. He's equally adept traversing hip hop, funk and soul. This ecelcticism is evidenced by his varied range of influences - from David Mancuso and Moodymann to The Unabombers and Bill Brewster; The Avalanches and Jim Sharp to Nicolas Jaar and Aaron Frazer.Today, Alan can be found alongside Matt Law at their Recommended By Celebrities residency at Strange Brew in Chorlton. This vinyl only night has a free and fluid range of musical influences, drawing from their diverse record collections.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/v1774810662/Alan_T_jdqgqf.png",
    "instagram": "https://www.instagram.com/recommended_by_celebrities/",
    "mixcloud": "https://www.mixcloud.com/RecommendedByCelebrities/",
    "soundcloud": "",
    "schedule": "Rhythm Rotation fri 7pm",
    "active": true
  },
  {
    "name": "Riggo",
    "slug": "riggo",
    "bio": "With over a decade of vinyl collecting, Riggo has emerged onto the scene as a dynamic DJ specialising in underground sounds.Digging through record shops across Europe, Riggo showcases a diverse array of hidden gems. With regular gigs in and around Chester, his soul, disco and house DJ sets are a reflection of his deep passion for music, blending genres to craft his unique identity.Riggo invites listeners on a journey through timeless grooves, sharing his carefully curated discoveries with every set.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/Riggo_z6avwq.png",
    "instagram": "https://www.instagram.com/riggo___/",
    "mixcloud": "https://www.mixcloud.com/Riggo_/",
    "soundcloud": "https://on.soundcloud.com/WDUeTRMmwRG42FGa9",
    "schedule": "Rhythm Rotation fri 7pm",
    "active": true
  },
  {
    "name": "Rhythm Rotation",
    "slug": "rhythm-rotation",
    "bio": "The Rhythm Rotation show is our guest DJ slot every week on Disc Break Radio. Featuring upcoming and established DJs from around the globe and covering all genres. Keep an eye on our socials for who's on this week.Want to hear your mix on the show? Get in touch here, we're always looking for new DJs & selectors",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/v1774810671/Rhythm_rotation_show_image_rchvfq.png",
    "instagram": "",
    "mixcloud": "",
    "soundcloud": "",
    "schedule": "Rhythm Rotation fri 7pm",
    "active": true
  },
  {
    "name": "Sparky",
    "slug": "sparky",
    "bio": "A DJ and vinyl aficionado for over 2 decades Sparky has a deep curiosity and passion for digging for old and new exotic sounds. He loves a cheeky European getaway during the regular school holidays to mooch around the shady record shops tucked down the winding backstreets in search for the next off-kilter Balearic bomb to unleash at his next set.Sparky has been bringing Balearic beats, Weirdo European pop, Chuggy Disco and Juicy rhythms to Liverpool through his Backyard Balearic and Melodies of Love events over the last decade. He has also been championing his digs through broadcasting on some of the finest radio stations such as Svara, Reform, Loose FM, Noods Radio, Brum Radio and Melodic Distraction. He has had the pleasure recently of Djing in venues across the city such as The Kazimier Gardens, The Buyers Club, Subrosa, Metrocola, Mother Espresso for events such as Moments Parties, Poolside Pumpers, Diggers Anthems and Deep Swing. Sparky also played for the whole evening down at Word of Mouth (W.O.M) over on the Santa Eulalia coast of Ibiza last year. Sparky is very much looking forward to finding the perfect venue to continue his Melodies of Love Event after the sad loss of Melodic Distraction and also has a record label with its first release Melodies Of Love 001 set to be unleashed on vinyl come May. Watch this space.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/sparky_zolibi.png",
    "instagram": "https://www.instagram.com/backyardbalearic/",
    "mixcloud": "https://www.mixcloud.com/thebaddsignal/",
    "soundcloud": "",
    "schedule": "Rhythm Rotation fri 7pm",
    "active": true
  },
  {
    "name": "imad:re",
    "slug": "imadre",
    "bio": "A Doctor by day and a DJ by night, imad:re has been making waves in the Manchester music scene since playing her first set at an open decks in September! Since then, she\u2019s played some serious venues such as XLR, Gorilla, The Deaf Institute, The DBA and has even made her London debut. imad:re loves digging for music in her free time to make sure her sets are full of high energy bangers and furious rhythms with some fun throwbacks sprinkled in there too.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/imadre_jgkhnc.png",
    "instagram": "https://www.instagram.com/imadre_dj",
    "mixcloud": "",
    "soundcloud": "https://soundcloud.com/imadre",
    "schedule": "Rhythm Rotation fri 7pm",
    "active": true
  },
  {
    "name": "Joe Strugs",
    "slug": "joe-strugs",
    "bio": "Doodle resident Joe Strugs drops a late-night jazzy mix to carry us through February. Cutting his teeth in London\u2019s club scene in 2015, he co-founded Damdon Music in Amsterdam and is now one third of Doodle Manchester, who have been curating unique and intimate parties across Manchester spaces for over a decade. Their music policy is not firmly rooted in any specific genre, but meanders surreptitiously through all walks of house, disco, Afro, funk, soul, electro and techno; beautifully weaving together sound and space. Joe brings a smooth blend of jazzy trip-hop, melodic house, Balearic grooves, nu-disco, and the occasional crowd classic.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/joestrugs_tbpd64.png",
    "instagram": "https://www.instagram.com/doodlemanchester/",
    "mixcloud": "",
    "soundcloud": "",
    "schedule": "Rhythm Rotation fri 7pm",
    "active": true
  },
  {
    "name": "Disorder213",
    "slug": "disorder213",
    "bio": "Hailing from Los Angeles, California, Robert Miranda & Aaron Quest are Disorder213 - Factory Records and Ha\u00e7ienda-inspired DJs & music curators.The pair host their own regular radio show on a local L.A. station and actively put on their own events.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/disorder213_logo_cqtytq.png",
    "instagram": "https://www.instagram.com/disorder213",
    "mixcloud": "",
    "soundcloud": "",
    "schedule": "Rhythm Rotation fri 7pm",
    "active": true
  },
  {
    "name": "Mike Dixon",
    "slug": "mike-dixon",
    "bio": "Mike started collecting vinyl over 30 years ago and is still wildly buying records today. His collection includes funk, soul, disco, boogie, nu-disco and house, with a penchant for the overseas flavours. He has a weekly show on Vinyl Night Radio, and can be seen playing at bars in the Stockport area from time to time!",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/mikedixon_fm7emh.png",
    "instagram": "https://www.instagram.com/mike_dxn/",
    "mixcloud": "https://www.mixcloud.com/MikeDxn/",
    "soundcloud": "",
    "schedule": "Rhythm Rotation fri 7pm",
    "active": true
  },
  {
    "name": "DJ Batehoven",
    "slug": "dj-batehoven",
    "bio": "Manchester-based DJ Batehoven brings a dynamic blend of classic house, UKG, hard house, and trance to the decks. After relocating from London, he's quickly established himself in Manchester's scene, becoming aresident at Workshop Events and playing at numerous venues across both cities. Currently, he's also expanding his creative output with original productions.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/djbatehoven_jyfykp.png",
    "instagram": "https://www.instagram.com/jamesbait/",
    "mixcloud": "",
    "soundcloud": "https://soundcloud.com/djbatehoven",
    "schedule": "Rhythm Rotation fri 7pm",
    "active": true
  },
  {
    "name": "Cafe Haus",
    "slug": "cafe-haus",
    "bio": "Caf\u00e9 Haus, Manchester-based event series spotlighting the deepest cuts from the \u201880s to now. With a focus on intimate spaces, B2B sets, and a loyal community, we champion underground sounds, vinyl gems, and pure dancefloor connection.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/cafehaus_veagax.png",
    "instagram": "https://www.instagram.com/cafe_haus_mcr/",
    "mixcloud": "https://www.mixcloud.com/thenightwithnoname/",
    "soundcloud": "",
    "schedule": "Rhythm Rotation fri 7pm",
    "active": true
  },
  {
    "name": "Fries With That",
    "slug": "fries with that",
    "bio": "Fries With That is your friendly neighbourhood DJ. He\u2019s cut his teeth at parties across Manchester including Parklife Festival, Ramona, XLR, Stage & Radio, Side Street Studio and The Yard. What began as an early fascination with the aux cable in his mate\u2019s baby blue Fiat Panda has now become a full blown obsession. His mixes for Discbreak Radio cover Chicago house, neon-tinged Italian disco and everything in-between. Get involved!",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/frieswiththat_hbfzdc.png",
    "instagram": "https://www.instagram.com/frieswthat/",
    "mixcloud": "",
    "soundcloud": "",
    "schedule": "Rhythm Rotation fri 7pm",
    "active": true
  },
  {
    "name": "Nablijven Soundsystem",
    "slug": "nablijven soundsystem",
    "bio": "Nablijven Soundsystem is an Amsterdam-based DJ collective of three members passionate about collection, mixing and editing the best in disco, funk, and house. Nablijven Soundsystem's sets are a journey through the depths of disco, house, and Italo, weaving together forgotten classics and fresh finds.When they\u2019re not performing, the trio can be found digging through record crates to uncover hidden gems, driven by a passion for discovery and reinvention.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/Nablijven_huglx5.png",
    "instagram": "https://www.instagram.com/nablijvenrcrds/",
    "mixcloud": "",
    "soundcloud": "https://soundcloud.com/nablijvenrecords",
    "schedule": "Rhythm Rotation fri 7pm",
    "active": true
  },
  {
    "name": "Nic Kozubik / Sour Mango",
    "slug": "nic kozubik",
    "bio": "\u201cTropical Balearica for Tropical B@$tards\u201dA sun-soaked journey through global rhythms, this mix for Disc Break Radio brings the heat with upbeat selections from Brazil, Colombia, Africa and beyond. Just pure tropical goodness, blended by Nic Kozubik under his Sour Mango alias.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/Nic_Kozubik_wdsyv2.png",
    "instagram": "https://www.instagram.com/sourmango_mcr/",
    "mixcloud": "https://www.mixcloud.com/DJNicKoz/",
    "soundcloud": "",
    "schedule": "Rhythm Rotation fri 7pm",
    "active": true
  },
  {
    "name": "Diliman",
    "slug": "diliman",
    "bio": "Deep vibes & raw groovesDiliman\u2019s universe is a deep dive into the essence of house and techno. A passionate vinyl digger for over 25 years, with a collection of more than 4,000 records, he crafts organic sets with finesse \u2014 blending deep waves, bouncy beats, and raw textures into his own sonic journey.His first international tour in South Africa in 2013 marked a turning point, helping him shape a unique and captivating sound that has evolved ever since. As a resident at KALT club in Strasbourg, he shares his most thrilling selections with genuine energy and intention.For the deep heads, the curious, the groove lovers \u2014 welcome to his world.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/Diliman_vwfxth.png",
    "instagram": "https://www.instagram.com/diliman_kalt/",
    "mixcloud": "",
    "soundcloud": "",
    "schedule": "Rhythm Rotation fri 7pm",
    "active": true
  },
  {
    "name": "Kassita",
    "slug": "kassita",
    "bio": "Kassita is an international DJ & producer who seamlessly blends a diverse range of electronic genres in her mixes, which are always infused with upbeat energy to get you stomping.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/Kassita_r4srhd.png",
    "instagram": "https://www.instagram.com/sita_sound/",
    "mixcloud": "",
    "soundcloud": "https://soundcloud.com/sita_sound#",
    "schedule": "Rhythm Rotation fri 7pm",
    "active": true
  },
  {
    "name": "Gravy Train",
    "slug": "gravytrain",
    "bio": "Get aboard the Gravy Train with Col and Wayne.From First Class Disco Edits to uplifting grooves and jacking House tracks from their collections; it'll be a journey that you won't want to be late for. See you on the platform. Choo Choo!",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/gravytrain_rgyftq.png",
    "instagram": "http://instagram.com/gravytraindjs",
    "mixcloud": "http://mixcloud.com/gravytraindj",
    "soundcloud": "",
    "schedule": "fri 5pm",
    "active": true
  },
  {
    "name": "Brad Davies",
    "slug": "braddavies",
    "bio": "Based in Ramsbottom, Brad is the resident DJ at The Coach in Edenfield, where he hosts the popular event Boogie Back Fri-Daze. He's also the voice behind The Boogie Boutique on Roch Valley Radio and recently launched his new Mixcloud series, Mixed With Love.Drawing inspiration from legends like Dave Lee (Z Records) and Ralph Tee (Expansion Records), Brad\u2019s signature blend of soulful grooves, disco, and boogie guarantees to get the dance floor moving.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/brad_davies_pnaqxl.png",
    "instagram": "https://www.instagram.com/dj_braddavies/",
    "mixcloud": "https://www.mixcloud.com/dj_braddavies/",
    "soundcloud": "",
    "schedule": "Rhythm Rotation fri 7pm",
    "active": true
  },
  {
    "name": "Gav Kemp",
    "slug": "gavkemp",
    "bio": "UK-born and Gold Coast-based DJ Gav Kemp has been spinning records since 1993, with over three decades of dedication to underground dance music culture. An avid vinyl collector with an uncompromising passion for hardcore, rave,Jungle UK garage and House, Gav's journey began in the underground - sneaking into events underage and following the legendary UK pirate radio scene that defined a generation.Early Career & UK ResidenciesGav's talent behind the decks earned him coveted residencies on London's influential pirate stations Point Blank FM and Shake FM during the late 90s. As internet radio emerged, he secured a residency on WorldDance Radio in Greenwich, marking his transition deeper into the UK garage scene while maintaining his love for house music's infectious grooves.Throughout the 2000s, Gav became a fixture on London's club circuit, playing at prestigious venues including the Mermaid Theatre and Glass House. His skills and reputation led to a resident position at the legendary Tru's Do's, operated by Tony Truman, owner of the iconic OBeach.Australian ChapterALways collecting vinly and moving to Australia in 2010, Gav found the local scene harder to crack during the height of the digital takeover. He stepped back for a few years, but as vinyl made its inevitable comeback, so did he. Now he's back doing what he's always done - playing proper records at bars and clubs across Australia, plus holding down a monthly slot on Ibiza Stardust Radio.I alwasy like to produce a mix that takes you on the journey, blending the vest best from my collection.",
    "image": "https://res.cloudinary.com/db5yf8okw/image/upload/Gav_Kemp_q4uhgz.png",
    "instagram": "https://www.instagram.com/gk_80_gc/",
    "mixcloud": "",
    "soundcloud": "https://soundcloud.com/masterg1",
    "schedule": "Rhythm Rotation fri 7pm",
    "active": true
  }
];